### ISSUE TITLE
Implement BuildBear/Custom Chain RPC Support

### ISSUE THREAD

**Issue by jewelsonn** [mark3labs/louper-v3#3]
Implement support for BuildBear Sandboxed Testnet/Mainnet so users can Use Custom Chain hosted by BuildBear.
Other things to consider:
- Ability to Use Abi  used in Sandbox EtherScan of Buildbear that were use to verified contract through its verification API url
- Alternatively Add custom Abi for unverified contracts
- Ability to edit Custom Chain info such as Chain ID, explorer url and api url

**Comment by ezynda3** [comment]
Can you paste some links to the projects you mentioned? E.g. I'm not sure what buildbear is.

**Comment by jewelsonn** [comment]
> Can you paste some links to the projects you mentioned? E.g. I'm not sure what buildbear is.

 Sure Here's their Git : [BuildBearLabs](https://github.com/BuildBearLabs)
 And here is their Website for users: https://www.buildbear.io/
 Their Docs:  https://docs.buildbear.io/docs/intro
 
 I am interested in their [Hardhat-Buildbear ](https://docs.buildbear.io/docs/Hardhat-Buildbear)  ([git](https://github.com/BuildBearLabs/Hardhat-BuildBear)) online  enverionment hosting where it gets easier to work on forked testnet/mainnet without issues using metamask. 
 
 The only issue sandbox verified contracts can't be identifed verifed by louper-v3 because its sandboxed online on a different forked chain of testnet/mainnet with a custom chain id and louper isn't able fetch their abi as it's not present where it's searching to retreive abi.
 
Try testing things using hardhat-buildbear as it saves a testnet.json file with all urls of rpc, explorer, faucet, etc specific to the deployed sandbox. Or you can simply use thier website too. It's also implemented on Ethereum Remix IDE as a plugin.

**Comment by jewelsonn** [comment]
@ezynda3 Will it be implemented? Or it's not good enough yet?
