### ISSUE TITLE
Implement River Protocol custom chain support testnet / mainnet

### ISSUE THREAD

**Issue by jterzis** [mark3labs/louper-v3#6]
We are developing a [messaging protocol](https://www.river.build/) that is currently deployed to testnet with a plan to deploy to mainnet soon. We would like to host River Protocol diamond contracts and associated facets on louper in order to aid node operators in inspecting and writing to our contracts for nodes that they operate in the network. River Protocol employs a custom op-stack based chain, River Chain, that currently is deployed in testnet with the following coordinates:

- chainId: 6524490
- [explorer](https://towns-devnet.explorer.caldera.xyz/)
- [rpcUrl](https://towns-devnet.rpc.caldera.xyz/http)
- [source](https://github.com/river-build/river-stage/tree/main/contracts/src/river)

**Comment by ezynda3** [comment]
So Louper currently uses Viem to source all of it's chain info. The best way to get support for a non-existent chain is to submit a definition to the Viem repo. https://github.com/wevm/viem/tree/main/src/chains/definitions

Also if the explorer has an api for fetching source code and ABIs make sure to add an `apiUrl` to the `blockExplorers` section there, otherwise Louper will not be able to fetch ABI information.

e.g.

```js
blockExplorers: {
    default: {
      name: 'Arbiscan',
      url: 'https://arbiscan.io',
      apiUrl: 'https://api.arbiscan.io/api',
    },
  },
  ```

**Comment by jterzis** [comment]
> So Louper currently uses Viem to source all of it's chain info. The best way to get support for a non-existent chain is to submit a definition to the Viem repo. https://github.com/wevm/viem/tree/main/src/chains/definitions
> 
> Also if the explorer has an api for fetching source code and ABIs make sure to add an `apiUrl` to the `blockExplorers` section there, otherwise Louper will not be able to fetch ABI information.
> 
> e.g.
> 
> ```js
> blockExplorers: {
>     default: {
>       name: 'Arbiscan',
>       url: 'https://arbiscan.io',
>       apiUrl: 'https://api.arbiscan.io/api',
>     },
>   },
> ```

Thank you @ezynda3 - we'll look into adding our chain info to Viem to get added!
